services:
  postgres:
    container_name: postgres
    image: docker.io/postgres:16
    restart: always
    networks:
      - carrental-network
    env_file:
      - env_pg_docker
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  car-rental:
    container_name: car-rental
    image: docker.io/mnaufalhilmym/car-rental
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./config.yml:/go/bin/config.yml

networks:
  carrental-network:
