app:
  mode: debug # debug, release, or test

web:
  address: :8080

log:
  print_level: DEBUG # TRACE, DEBUG, INFO, WARN, ERROR, OFF
  stacktrace_level: ERROR # TRACE, DEBUG, INFO, WARN, ERROR, OFF
  max_pc: 10 # maximum stacktrace program counter

db:
  host: postgres
  port: 6543
  user: carrental_user
  password: PaF7UybfCHdEnF65
  name: carrental_db
  pool:
    idle: 10
    max: 100
    lifetime: 300

validator:
  phone_number: "^08[0-9]{8,11}$"
